"""
scons build file

pem: drv_mng

@author: Jean-Lou Dupont
"""

Import('env')

d = env.Dictionary()

#no difference at this point
if d.get('_DEBUG', False):
	#DEBUG
	libs=['libpem_common_debug', 'phidget21']
	pr = env.SharedLibrary('pem_drv_mng_debug', Glob("src/*.cc"), LIBS=libs )	
	env.Install('/usr/local/lib', '#pem/drv_mng/debug/libpem_drv_mng_debug.so')
else:
	#RELEASE
	libs=['libpem_common', 'phidget21']
	pr = env.SharedLibrary('pem_drv_mng', Glob("src/*.cc"), LIBS=libs )
	env.Install('/usr/local/lib', '#pem/drv_mng/release/libpem_drv_mng.so')
	
Default(pr)

env.Alias('installlib', '/usr/local/lib')