"""
scons build file

pem: drv_mng

@author: Jean-Lou Dupont
"""

Import('env')

d = env.Dictionary()

#no difference at this point
if d.get('_DEBUG', False):
	#DEBUG
	libs=['libpem_common_debug', 'phidget21', 'rt']
	pr = env.Program('pem_drv_mng_debug', Glob("src/*.cc"), LIBS=libs )	
	env.Install('/usr/bin', '#pem/drv_mng/debug/pem_drv_mng_debug')
else:
	#RELEASE
	libs=['libpem_common', 'phidget21', 'rt']
	pr = env.Program('pem_drv_mng', Glob("src/*.cc"), LIBS=libs )
	env.Install('/usr/bin', '#pem/drv_mng/release/pem_drv_mng')
	
Default(pr)

env.Alias('install', '/usr/bin')