"""
scons build file

@author: Jean-Lou Dupont
"""

Import('env')

d = env.Dictionary()

if d.get('_DEBUG', False):
	libs=['pthread','litm_debug','phidget21','ei']
else:
	libs=['pthread','litm','phidget21','ei']

pr = env.Program('phidgetmanager', Glob("src/*.cc"), LIBS=libs )
Default(pr)
	
