"""
scons build file

@author: Jean-Lou Dupont
"""

Import('env')

d = env.Dictionary()

#no difference at this point
if d.get('_DEBUG', False):
	libs=[]
else:
	libs=[]

pr = env.SharedLibrary('drv_common', Glob("src/*.cc"), LIBS=libs )
Default(pr)
	
